# Job controls
job:
  name: "UKESM_data_download"
  l_batch: True
  l_download: True
  l_copy_downloaded: False
  l_convert: True
  l_copy_converted: True

# SLURM settings
slurm:
  account: "acsis"
  partition: "standard"
  qos: "short"
  time: "4:00:00"
  memory: "200000"
  array_range: "1-25"

# Paths
path:
  tmp_dir: "/work/scratch-pw2/vs480"
  downloaded_save_dir: "/gws/nopw/j04/acsis/vs480/model_output" # optional
  converted_save_dir: "/gws/nopw/j04/acsis/vs480/model_output" # optional
  # relative to working directory
  processing_queue: "./processing_queues/processing_queue_u-br438.csv"

# Retrieving options
download:
  l_extra_query: False
  max_retries: 3 # optional
  # query_options: "./query_options.txt"

# Processing options
convert:
  l_use_downloaded_save_dir: False # optional. For converting from pp files in downloaded_save_dir
  conda_env: "cmip6-env"
  format: "nc" # 'nc' or 'zarr'
